Some basic getopts integration
Usage: launch-pangeo-on-cheyenne -u USERNAME [-A ACCOUNT -i JOBID -H REMHOST]
       USERNAME - ssh to cheyenne with 'ssh USERNAME@cheyenne.ucar.edu'
       ACCOUNT - account key to charge for running jupyter lab
       JOBID - Existing job ID of jupyter lab running on cheyenne
       REMHOST - Compute node currently running jupyter lab
 USERNAME is always required. Provide ACCOUNT to launch a new job, otherwise
 provide either JOBID or REMHOST

Still want to add a few more options, but this is a good start

diff --git a/launch-pangeo-on-cheyenne b/launch-pangeo-on-cheyenne
--- a/launch-pangeo-on-cheyenne
+++ b/launch-pangeo-on-cheyenne
@@ -1,7 +1,19 @@
 #!/bin/bash
 #
 # USAGE: Launch this script from a local machine, it will connect to cheyenne as needed
-# Required argument: user name
+# Required arguments:
+# - user name
+# - account key to charge
+#
+# Optional arguments:
+# - job id OR job name (if reconnecting to existing lab)
+# - walltime requested (default 3 hours)
+#
+# Things user can change by editing script:
+# - queue / node & core count (recommend requesting single core via share queue)
+# - root directory to launch lab from (default: /glade/work/$USER)
+#
+# ABOUT:
 # This script handles two distinct tasks:
 # 1. submit a job to cheyenne queue to start jupyter remotely
 #    - wait for the job to start running
@@ -13,35 +25,67 @@
 # => also want a way to skip step 1 and connect to a running job
 #
 
-if [ $# -ne 1 ]; then
-  echo "$(baseline $0) requires a single argument: user name for logging in to cheyenne"
+function usage () {
+  echo "$($0 -h)"
+}
+# Parse getopts
+# Abort if user not specified
+while getopts "u:A:i:H:h" opt; do
+  case $opt in
+    u)
+      REM_USER=$OPTARG
+    ;;
+    A)
+      ACCOUNT=$OPTARG
+    ;;
+    i)
+      JOBID=$OPTARG
+    ;;
+    H)
+      REM_HOST=$OPTARG
+    ;;
+    h|\?)
+      echo "Usage: $(basename $0) -u USERNAME [-A ACCOUNT -i JOBID -H REMHOST]"
+      echo "       USERNAME - ssh to cheyenne with 'ssh USERNAME@cheyenne.ucar.edu'"
+      echo "       ACCOUNT - account key to charge for running jupyter lab"
+      echo "       JOBID - Existing job ID of jupyter lab running on cheyenne"
+      echo "       REMHOST - Compute node currently running jupyter lab"
+      echo " USERNAME is always required. Provide ACCOUNT to launch a new job, otherwise"
+      echo " provide either JOBID or REMHOST"
+      exit 0
+    ;;
+    *)
+      echo "Invalid option: -$opt" >&2
+      exit 1
+    ;;
+  esac
+done
+
+# Check for required arguments
+# Always require user for logging in to cheyenne
+# Either need account to charge (for launching jupyter) OR a job id / compute node name of running jupyter
+if [ -z $REM_USER ] || { [ -z $ACCOUNT ] && [ -z $JOBID ] && [ -z $REM_HOST]; }; then
+  usage
   exit 1
 fi
-REM_USER=$1
 
 #######################################
 ### THIS FUNCTION LAUNCHES JUPYTER
 ### (RUN IT ON CHEYENNE)
 function launch_job () {
+  # Several variables passed through call to launch_job
+  REM_USER=$1
+  ACCOUNT=$2
+
   ### OPTIONS THAT USERS SHOULD SET FOR CHEYENNE
   QUEUE=share
-  #QUEUE=economy
-  ACCOUNT=`cat ~/.cesm_proj`
   NODES=1
   CORES=1
   HOURS=3
-  ROOT_PATH=/glade/work/mlevy/codes/pangeo-tutorial-august-2018
+  ROOT_PATH=/glade/work/${REM_USER}/
   SET_PY_ENV="source activate pangeo"
-  LAUNCH_JLAB=./start-jlab
+  LAUNCH_JLAB=./codes/pangeo-tutorial-august-2018/start-jlab
 
-  ### ACTUALLY  RUN THE JOB
-  # 1) Submit to queue
-  # QSUB_OPTS="-l inception=login -l walltime=${HOURS}:00:00 -l select=${NODES}:ncpus=${CORES}:mpiprocs=${CORES} -A ${ACCOUNT} -j oe -r n -m be -S /bin/bash -V -q ${QUEUE}"
-  # SUBMIT="qsub ${QSUB_OPTS} -N pangeo"
-  # RUNCMD="export LD_LIBRARY_PATH= ; ${SET_PY_ENV} ; cd ${ROOT_PATH} ; ${LAUNCH_JLAB}"
-  # echo "Running: ${RUNCMD}"
-  # echo "Submitting with: ${SUBMIT}"
-  # echo "${RUNCMD}" | ${SUBMIT}
   # 1) Submit job
   s=$(qsub << EOF
   #!/bin/bash
@@ -101,14 +145,13 @@ EOF
 ### ALSO FORWARDS DASK DASHBOARD TO
 ### https://localhost:8787
 function create_tunnel () {
-  REM_HOST=`grep Job\ host .last_run.log | cut -d ':' -f 2 | cut -d '/' -f 1 | tr -d ' '`
   cmd="ssh -N -l ${REM_USER} -L 8888:${REM_HOST}:8888 -L 8787:${REM_HOST}:8787 cheyenne.ucar.edu"
   echo $cmd
   nohup $cmd &
   tunnel=$!
 
   # ^C should kill the tunnels
-  trap "kill -9 $tunnel; exit 1" INT
+  trap "kill -9 $tunnel; rm -f .last_run* nohup.out; exit 0" INT
 
   echo "Use ^C to kill ssh tunnel"
   while [ 1 ]; do
@@ -118,14 +161,42 @@ function create_tunnel () {
 #######################################
 
 #######################################
+### This function gets remote host given job ID
+### Written as a function to avoid "qstat not found" error
+function get_REM_HOST () {
+  echo `qstat -x -f $1 | grep exec_host | awk -F= '{print $2}'`
+}
+#######################################
+
+#######################################
 ### MAIN SCRIPT
 # 1) RUN launch_job ON CHEYENNE
-ssh cheyenne.ucar.edu /bin/bash << EOF | tee .last_run.log
-  $(declare -f launch_job)
-  launch_job
+if [ -z $JOBID ] && [ -z REM_HOST ]; then
+  ssh ${REM_USER}@cheyenne.ucar.edu /bin/bash << EOF | tee .last_run.log
+    $(declare -f launch_job)
+    launch_job ${REM_USER} ${ACCOUNT}
 EOF
+  REM_HOST=`grep Job\ host .last_run.log | cut -d ':' -f 2 | cut -d '/' -f 1 | tr -d ' '`
+fi
 
 # 2) RUN create_tunnel AFTER CHEYENNE JOB LAUNCHES
+if [ -z $REM_HOST ]; then
+  if [ ! -z $JOBID ]; then
+    echo "Getting remote host from Job ID..."
+    ssh ${REM_USER}@cheyenne.ucar.edu /bin/bash << EOF | tee .last_run.host
+    $(declare -f get_REM_HOST)
+    get_REM_HOST $JOBID
+EOF
+    REM_HOST=`cat .last_run.host | cut -d '/' -f 1`
+    if [ -z $REM_HOST ]; then
+      echo "Unable to determine host from provided job ID"
+      exit 1
+    fi
+  else
+    echo "Can not determine remote host!"
+    exit 1
+  fi
+fi
 if [ $? -eq 0 ]; then
   create_tunnel
 fi
